POST http://localhost/member HTTP/1.1
content-type: application/json

{
    "fullname": "robby awaldi",
    "email": "robbyawaldi@gmail.com",
    "password": "zxcasd"
}

###
GET http://localhost:8080/member HTTP/1.1
content-type: application/json

###
GET http://localhost:8080/member/602740e98faba807009f0383 HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8080/member/602740e98faba807009f0383 HTTP/1.1
content-type: application/json

###
PATCH http://localhost:8080/member/602743c91fd6672cf470df79 HTTP/1.1
content-type: application/json

{
    "email": "robbyawaldi.mtech@gmail.com"
}