version: '3'

services: 
  be:
    container_name: mern_be
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on: 
      - db
    networks: 
      - mern-app

  db:
    container_name: mern_db
    image: mongo
    volumes: 
      - mongo-data:/data/db
    networks: 
      - mern-app

networks: 
  mern-app:
    driver: bridge

volumes: 
  mongo-data:
    driver: local